### PR TITLE
Added TogglePause on MusicRoom

### PR DESCRIPTION
**Pull request by Neyunse**
If music is currently playing it will pause, otherwise it will resume from where it stopped.
In case a music has already finished, the queue will play the music again from the beginning the next time it is called.
If the music is playing the button will receive the selected status and when paused it will be removed.

Note:
`__MusicRoomTogglePause` is based on `__MusicRoomStop`, because in some tests in my project, if `__MusicRoomTogglePause` was the same as `__MusicRoomTogglePlay` it caused some data about the music being played added using `add(action=[SetVariable("jb_title", title)])` not to be displayed.

Inspired by the report I did before #3054

### CODE REVIEW

**Comment by renpytom** [comment]
Ah, shoot - before I saw this, I already implemented MusicRoom.TogglePause. 

Can you try out  ad8ff33bd and make sure it fixes the SetVariable issue?

**Comment by Neyunse** [comment]
> Ah, shoot - before I saw this, I already implemented MusicRoom.TogglePause.
> 
> Can you try out [ad8ff33](https://github.com/renpy/renpy/commit/ad8ff33bd4ac1692fccbb70a0be5d264486c59fb) and make sure it fixes the SetVariable issue?

No, the data is not displayed. Appears only "()"

screenshot-0004

This is how it should look

screenshot-0005

**Comment by Neyunse** [comment]
@renpytom I discovered a solution, and it is to add ```
def periodic(self, st):
            
            self.mr.periodic(st)

            return .1
```

https://github.com/Neyunse/renpy/blob/master/renpy/common/00musicroom.rpy#L142

**Comment by renpytom** [comment]
Merged, thanks.

**Pull request merged**
