### PR TITLE
Add scattered configuration variables to main list

### LINKED ISSUE #3597: Link  scattered configuration variables to the main list
Based on #3586 and #3589 I propose to including configuration variables that are not in the general list.

scattered configuration variables:
https://www.renpy.org/doc/html/nvl_mode.html#config-variables
https://www.renpy.org/doc/html/side_image.html
https://www.renpy.org/doc/html/self_voicing.html#var-config.descriptive_text_character
https://www.renpy.org/doc/html/preferences.html#audio-channel-defaults
https://www.renpy.org/doc/html/model.html
https://www.renpy.org/doc/html/achievement.html#var-config.steam_appid
https://www.renpy.org/doc/html/gesture.html
https://www.renpy.org/doc/html/live2d.html

### PR DESCRIPTION
**Pull request by Moshibit**
attempt to fix #3597. I hope I understood how Sphinx works.

### CODE REVIEW

**Comment by Gouvernathor** [comment]
No, :ref: isn't what you want, config variable references are a bit more annoying than that.

**Comment by Moshibit** [comment]
I see, I have to use :var:``

**Comment by Gouvernathor** [comment]
Yep, you can take the changelog.rst page as an example, it references config variables a lot.

**Comment by Moshibit** [comment]
@Gouvernathor, what do you think now?

**Comment by Gouvernathor** [comment]
Yep, it's fine, although I'll add a bit of a text body around to introduce them.

**Comment by Moshibit** [comment]
Thank you

**Pull request merged**
