### PR TITLE
Configuration variables for audio volumes

### PR DESCRIPTION
**Pull request by vollschauer**
I would like to have something like this, not sure if the "set_volume" code syntax is correct ;)

### CODE REVIEW

**Comment by renpytom** [comment]
Please add documentation to sphinx/source/config.rst, and then I'll merge this.

**Comment by vollschauer** [comment]
I have added it at the end of the "Preference Defaults" section. Better proof read it ;) I didn't know what documentation is before...

**Comment by renpytom** [comment]
I've merged this. I also renamed the variables to config.default_music_volume (etc), since I don't like abbreviations in the public API.

**Comment by vollschauer** [comment]
Nice! Thank you ;)

**Pull request merged**
