### PR TITLE
Pause audio when window is minimized

### PR DESCRIPTION
**Pull request by jsakaa**
Attempted implementation of #2645. Governed by a preference; should pause all audio tracks when the game window is minimized and resume them when it is maximized by default.

### CODE REVIEW

**Comment by Booplicate** [comment]
Let's say developer (or user via a button action) paused music. Would changing focus unpause music? Looking at the code I think it would. But I'd say it's not expected - we shouldn't unpause music which was intentionally paused before.

**Comment by Gouvernathor** [comment]
If parts of the code need to be re-done for the reasons stated above (and that's a big if), and if there are no technical advantages to pausing, I would slightly prefer the sound be muted rather than paused.
One reason would be that fullscreen games work more that way, in my experience. Another would be that ATL and screen timers and time-taking elements of renpy won't be paused in the meantime.

**Comment by Booplicate** [comment]
Actually, I agree, I'd also prefer the sound to be muted than paused. If I recall correctly there's also one special channel (`audio`?) which can't be paused either?

**Comment by jsakaa** [comment]
> Let's say developer (or user via a button action) paused music. Would changing focus unpause music?

I had the same concern, but it shouldn't as it is currently. 
It's a little ambiguously written but the boolean that governs whether the audio should unpause upon changing focus only becomes True if there was a matching minimization of the window beforehand. I should probably give that value a better name, since 'audio_paused' is somewhat misleading in hindsight.
So that is to say that just changing mouse or keyboard focus for instance shouldn't trigger audio to unpause.

> But I'd say it's not expected - we shouldn't unpause music which was intentionally paused before.

I don't believe it would, since this sort of mirrors the functionality of the 'check_suspend()' function earlier in the file for Android. I brought this worry up to Tom over Discord and that was the conclusion he came to as well.

I do also agree that muting would be preferable to pausing, though, since that does model the behavior of most games in my experience as well. I'll try to see to making that change.

**Comment by Gouvernathor** [comment]
Just to dig in on that risk of mistakenly unpausing things, and this may be an unnecessary concern - what if I have a paused channel, and another upaused channel, and I minimize and reopen the game ? It will leave the fist channel as it was, and unpause the second channel ?

**Comment by jsakaa** [comment]
> It will leave the fist channel as it was, and unpause the second channel ?

I believe that would be the behavior, looking at this snippet of relevant code from 'periodic()' in the 'channel' class in 'audio.py'.

As per my understanding,
after 'pause_all()' is called, I think that for the channel that was already paused by the developer/user, 'self.context.pause' would be True, as would be 'global_pause', making 'want_pause' equal to True as well. Then, 'self.paused' would equal 'want_pause' meaning the condition is not met and that this already paused channel would remain paused.
After, when the user maximizes the window and 'unpause_all()' is called, 'self.context.pause' would still be true even if 'global_pause' is now false, meaning that 'want_pause' would be equal to True. 'self.paused' would still be equal to True as it was not changed earlier, meaning that once again the condition is not met and the channel is not unpaused.

Though please let me know if I've had a misunderstanding! 

```
want_pause = self.context.pause or global_pause

if self.paused != want_pause:

            if want_pause:
                self.pause()
            else:
                self.unpause()

            self.paused = want_pause
```

**Comment by renpytom** [comment]
This looks good to me - I'm merging it now. Thank you for the contribution.

**Pull request merged**
