### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by Julvenzor**
Minor corrections and translation in Spanish.

Regards.

### CODE REVIEW

**Comment by Gouvernathor** [comment]
You can edit files from [your copy of the repository](https://github.com/Julvenzor/renpy/tree/patch-3), and have them all in the same translation pull request.

**Comment by Julvenzor** [comment]
I'm sorry. I'm a just a translator. I don't know coding or how to use GitHub properly.
Thanks for your help.

**Comment by Gouvernathor** [comment]
No worry, it's fine

**Comment by Julvenzor** [comment]
Perfect! Now I know how to do it.
Thank you so much. :)

**Pull request merged**
