### PR TITLE
Update distribute_gui.rpy

### PR DESCRIPTION
**Pull request by renoa**
translate, i hope i'm doing this right haha

### CODE REVIEW

**Comment by caryoscelus** [comment]
Perhaps it would be a better idea to make one pull request for all
translation changes.

**Comment by renoa** [comment]
so sorry >< i'd done with translations for today. but i'm getting an error for a missing font file so i'm gonna go through all the stuff i screwed up by assigning a different font file and fix them ^^ 
i'll try to remember to make only one pull request haha so sorry i'm a noob

**Comment by renpytom** [comment]
Just let me know when you're ready for me to pull these.

**Comment by renpytom** [comment]
I merged them, since I didn't see any font problems (and don't, after testing).

**Pull request merged**
