### PR TITLE
SChinese update for new Ren'Py

### PR DESCRIPTION
**Pull request by zedraxlo**

### CODE REVIEW

**Comment by renpytom** [comment]
Is this not supposed to go in?

**Comment by zedraxlo** [comment]
> Is this not supposed to go in?

I accidentally changed the line break from LF to CRLF, which caused us to not be able to see the difference.
I think I should re-upload it once using LF to see the difference.

**Comment by renpytom** [comment]
Ah, makes sense. Thanks. Let me know when it's ready and I'll merge it.

**Comment by zedraxlo** [comment]
> Ah, makes sense. Thanks. Let me know when it's ready and I'll merge it.

New one ready. Changes can now be displayed.

**Pull request closed without merging**
