### PR TITLE
Create splash_screen.rpy

### PR DESCRIPTION
**Pull request by YasPHP**
Good to go?

### CODE REVIEW

**Comment by renpytom** [comment]
Why do we want this? Ren'Py supports them, since people like them - but since it strictly slows the game down, I don't think it needs to be encouraged like this.

**Comment by YasPHP** [comment]
Ah okay, thought it could be a good move to promote general game logistics like copyright notice, version, etc.

**Comment by renpytom** [comment]
Oh, those go in the about screen, which is part of the default gui.

**Comment by YasPHP** [comment]
Awesome, thanks for clarifying.

**Pull request closed without merging**
