### PR TITLE
Add min, max arguments for actions

### PR DESCRIPTION
**Pull request by via-my**
A simple idea that will make our life easier.

From:
`SetVariable('value', min(5, max(0, value + 1)))`
To:
`SetVariable('value', value + 1, max=5, min=0)`

### CODE REVIEW

**Comment by Andykl** [comment]
I don't think we should add such thing to the language. I can imagine some other "usefull once per 69 cases" keywords.
Moreover, because I also needed invrement/decrement actions I made my own `IncrementVariable(variable_name, amount=1, max=None)` and `DecrementVariable(variable_name, amount=1, min=None)`, and their additional benefit is that they are constant, whereas `SetVariable(variable_name, value, min=None, max=None)` is not (in case `value` is not a constant).

**Comment by via-my** [comment]
Good idea. Let's propose `IncrementVariable` and `DecrementVariable` then.

**Comment by via-my** [comment]
But then we should write `IncrementVariable`, `IncrementFieldVariable`, `IncrementScreenVariable`, `IncrementLocalVariable`, `IncrementDict` and `Decrement`...

**Comment by Numerlor** [comment]
What exactly is wrong with `SetVariable('value', min(5, max(0, value + 1)))`? If the nested min/max is the issue, you can just define your own clamp function

**Comment by via-my** [comment]
Basically, this is more about simplification, time saving and code readability for a common novel developer.
It will be a little bit faster to read and edit code, especially when there will be no need to worry about the closing braces or any other non eye-catching symbols. Sometimes, it may be a time consuming task for big projects that require 30sec> to load, since if there will be a small syntax mistake, the whole project will be closed.
```
action SetScreenVariable('page', clamp(page + 1, 0, int(len(GALLERY_DICT) / per_page)))
```
```
action SetScreenVariable('page', page + 1, min=0, max=int(len(GALLERY_DICT) / per_page))
```

**Comment by Booplicate** [comment]
It doesn't improve readability to me. It's more explicit, but not in a good way.
Also since it's just one of use cases of `SetVariable`, it feels weird having a set of parameters just for that.

**Comment by renpytom** [comment]
I think for this sort of thing, it's best to keep the built-in actions simple, and then let the creators define their own actions (or functions that return actions). 

For example:

```renpy
init python:
    def SetClampedVariable(variable, value, minimum=0, maximum=100):
         value = max(value, minimum)
         value = min(value, maximum)
         return SetVariable(variable, value)
```

Ren'Py is designed to make this really simple (some of the built-in actions are just functions returning actions), and so I think this sort of thing should be encouraged.

**Comment by via-my** [comment]
If the renpy coding philosophy is like so, then I quite understand it. Thanks for your time, guys.

**Pull request closed without merging**
