### PR TITLE
Add RPi4 Raspbian Support.

### PR DESCRIPTION
**Pull request by lee-yunseok**
Just linked aarch64 to current armv7l RPi libs. At least until now, I haven't found any problems.

### CODE REVIEW

**Comment by uyjulian** [comment]
I thought RPi4 is armv8 not armv7l

**Comment by lee-yunseok** [comment]
RPi4 is armv8 but armv7l libs work for RPi4. No need make armv8 libs on Ren'Py.

**Comment by uyjulian** [comment]
This may break Linux 4 Tegra and other native arm64 bit distributions

**Comment by lee-yunseok** [comment]
Is this break switch homebrews?

**Comment by uyjulian** [comment]
No, since it is not using Linux.

However, other native aarch64 platforms may be broken due to not having 32 bit libraries.

**Comment by uyjulian** [comment]
Looks good. May I suggest squash

**Comment by lee-yunseok** [comment]
@uyjulian I have considered the expected situation. Now it looks safe.

**Comment by uyjulian** [comment]
You should squash your commits.

**Comment by lee-yunseok** [comment]
The only one issue is lacking performance in Raspbian 64bit kernel with libegl error. I believe this will be solved with next mesa.

**Comment by lee-yunseok** [comment]
libEGL problem has solved in recent RPi update.

**Comment by lee-yunseok** [comment]
libEGL error has solved in recent RPi update.

**Pull request closed without merging**
