### PR TITLE
add local/nested labels support

### PR DESCRIPTION
**Pull request by caryoscelus**
Originally proposed here: https://lemmasoft.renai.us/forums/viewtopic.php?f=32&t=38122

> When the script is heavy-choice, amount of labels can soon get unmanageable. I think the usual way to avoid name collisions is to use something like "chapter1_episode1_choice1", but it is ugly, verbose and still doesn't guarantee avoidance of collisions, especially when using third-party code.
> 
> To resolve this problem i propose introducing 'local' labels, which can have identical names inside different 'global' labels. Here's how it works:
> 
> ```renpy
> label global_label:             # normal label, nothing changed for its behaviour
>   "..."
> label .a:                       # local label fully identified as global_label.a
>   "..."
>   jump .a                       # local jump, resolved to global_label.a
> 
> label another_global_label:
>   "..."
> label .a:                       # another_global_label.a
>   jump global_label.a
> ```
> 
> Syntax-wise, it's fully backwards compatible since currently label names cannot contain dot and thus all existing labels are considered global with this change.
> 
> It is also possible to expand this idea to have no nesting limit (i.e. making possible to have label a.b.c.d and jump to it inside a.b.c scope by simply "jump ...d")
> 
> I also found out that it is currently possible to 'nest' labels using indentation, but it doesn't protect from name collisions. It is possible to implement the same mechanism with such nested labels, but since it uses old syntax, it can cause problems with existing code. Also, it is more visual which can sometimes be good, but can also be bad when you prefer all statements to be on same indentation level.

While waiting for comments, i finished implementing it anyway and so making this pr for more specific discussion. If this is going to be accepted, i'll mention this in docs as well.

### CODE REVIEW

**Comment by renpytom** [comment]
I like this - I think it solves a problem and should be relatively easy to explain. 

I think my one concern is that local labels could cause problems with the translation system, which is probably not expecting a . in the label syntax. This can likely be solved by making all local labels hidden labels. 

Really, my main concerns with this are that I was too sick to answer you on the forum, and that I didn't come up with this myself. It looks good, and after the local labels are hidden by default, I think it's ready to merge once it it documented.

**Comment by caryoscelus** [comment]
Hmm, translation does indeed fail with this. I think the easiest way is simply to fix `Lexer.hash` (doesn't seem like a proper name for translation id parsing, btw) to accept `.`. That seem to work. Or if that looks bad, another option would be to replace `.` for `_` in translation strings.

**Comment by renpytom** [comment]
I think I like the idea of making local labels hidden. They feel like they should be as anonymous as possible - invisible to code outside the named label, at least for purposes like translations.

**Comment by caryoscelus** [comment]
I think that depends on usage pattern, i.e. balance between global and local labels.

Just fixed ability to declare labels in form of `global.local` with `global` mismatching current scope. I wonder if `global.local` form should be forbidden altogether for declarations. The only time when it makes sense to use them is if you've got a lot of code between global label and local one and want to remind the scope.

Also, do you think it would make sense to allow more nesting levels?

**Comment by renpytom** [comment]
I think one level is fine, and anything more would be excessive.

**Comment by Shizmob** [comment]
I think leaving local labels visible might be nice, also to be able to create a sense of hierarchy.

**Comment by renpytom** [comment]
Okay, then let's have the dot replaced with _ when generating translates.

**Comment by caryoscelus** [comment]
Looks like that would require a bit more changes than i suspected.

**Comment by caryoscelus** [comment]
For some reason, adding `identifier = identifier.replace('.', '_')` into `ScriptTranslator.lookup_translate` seems to work for one or two statements, but then fails with `Exception: Translation nodes cannot be run directly.`

**Comment by caryoscelus** [comment]
Translation seems to be fixed, some documentation added.

**Comment by vollschauer** [comment]
I'm really looking forward to this ....could sure use it right now ;)

**Comment by caryoscelus** [comment]
Not sure why it wasn't merged yet, i think it was ready. Now there are some conflicts though. Will check them out soonish.

**Comment by vollschauer** [comment]
Just curious, if the local labels will work also if there are indented inside in a "if else" statement?

**Comment by caryoscelus** [comment]
Not sure what you mean. Can you give an example?

**Comment by vollschauer** [comment]
This example is maybe silly but you get an idea what I mean:
`label test:
    if something == 0:
        if something1 == 0:
            if something2 == 0:
                if something3 == 0:
                $ something = "something"
                jump .local

        .local 

        if something4 == 0:
           if something5 == 0:
               $ something1 = "something1"`

**Comment by caryoscelus** [comment]
Not sure if it's a good idea, but something like that (only syntax is a bit different) already works with normal labels, so should work with local as well.

```renpy
label test:
    if True:
        "True"
        jump false_as_well
    else:
        label false_as_well:
            pass                # used to avoid indentation increasing
        "False"
```

**Comment by renpytom** [comment]
Merged this in. Thank you.

**Pull request merged**
