### PR TITLE
Update 00library.rpy

### PR DESCRIPTION
**Pull request by Meithal**
I get a crash here for some reason when trying to start the game, this prevents the crash and keep the functionality

### CODE REVIEW

**Comment by Gouvernathor** [comment]
What exactly is the error ? Does it show what element is not there to be removed ?

**Comment by mal** [comment]
Is it possible that you are redefining `set` in a `python early` block?

**Comment by Meithal** [comment]
Full traceback

Full traceback:
  File "/Users//IdeaProjects/patronus/sdk/renpy/bootstrap.py", line 274, in bootstrap
    renpy.main.main()
  File "/Users//IdeaProjects/patronus/sdk/renpy/main.py", line 558, in main
    renpy.game.context().run(node)
  File "renpy/common/00library.rpy", line 299, in script
    init -1000 python:
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python3.9/site-packages/future/utils/__init__.py", line 441, in raise_
  File "renpy/common/00library.rpy", line 299, in script
    init -1000 python:
  File "/Users//IdeaProjects/patronus/sdk/renpy/ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users//IdeaProjects/patronus/sdk/renpy/python.py", line 1049, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00library.rpy", line 398, in <module>
    renpy.lint.renpy_builtins.remove(i)
  File "/Users//IdeaProjects/patronus/sdk/renpy/revertable.py", line 97, in do_mutation
    return method(self, *args, **kwargs)
KeyError: 'ease'

While running game code:
  File "renpy/common/00library.rpy", line 299, in script
    init -1000 python:
  File "renpy/common/00library.rpy", line 299, in script
    init -1000 python:
  File "renpy/common/00library.rpy", line 398, in <module>
    renpy.lint.renpy_builtins.remove(i)
KeyError: 'ease'

Im not redefining globals AFAIK

**Comment by Gouvernathor** [comment]
If you're using VSCode or Atom, could you open your project, hit Ctrl+Shift+F, search for `ease` and try to find any python, dollar or define line ? (anything that not just a `with` line basically)

This is the symptom of another issue, so even if it reveals to be benign, I'd rather know what it is before dismissing the symptom.

**Comment by Meithal** [comment]
Nothing seems to declare an ease variable

**Comment by Meithal** [comment]
This is a globals() dump right before the crash

  File "renpy/common/00library.rpy", line 312, in <module>
    raise Exception(list(globals()))
Exception: ['__name__', '__package__', '__builtins__', '__doc__', '__loader__', '__spec__', '__file__', '__cached__', 'division', 'absolute_import', 'with_statement', 'print_function', 'unicode_literals', 'PY2', 'basestring', 'bchr', 'bord', 'chr', 'open', 'pystr', 'range', 'round', 'str', 'tobytes', 'unicode', 'xrange', 'python_list', '_list', 'python_dict', '_dict', 'python_object', '_object', 'python_set', '_set', '_type', '__renpy__list__', 'list', '__renpy__dict__', 'dict', '__renpy__set__', 'set', 'Set', 'object', 'sorted', 'ui', '__', 'eval', 'absolute', 'renpy', '_print', 'print', '_', '_p', 'input', 'raw_input', 'im', 'anim', '_restart', '_return', '_args', '_kwargs', '_window', '_window_subtitle', '_rollback', '_begin_rollback', '_skipping', '_dismiss_pause', '_config', '_widget_by_id', '_widget_properties', '_text_rect', '_menu', 'main_menu', '_autosave', '_live2d_fade', '_Config', 'style', 'config', 'library', 'Bar', 'Button', 'ImageButton', 'Input', 'TextButton', 'ImageReference', 'DynamicImage', 'Image', 'Frame', 'Borders', 'Solid', 'FileCurrentScreenshot', 'LiveComposite', 'LiveCrop', 'LiveTile', 'Composite', 'Crop', 'Tile', 'Flatten', 'Null', 'Window', 'Viewport', 'DynamicDisplayable', 'ConditionSwitch', 'ShowingSwitch', 'AlphaMask', 'Transform', 'Animation', 'Movie', 'Particles', 'SnowBlossom', 'Text', 'ParameterizedText', 'FontGroup', 'Drag', 'DragGroup', 'Sprite', 'SpriteManager', 'Matrix', 'Live2D', 'Model', 'Alpha', 'Position', 'Pan', 'Move', 'Motion', 'Revolve', 'Zoom', 'RotoZoom', 'FactorZoom', 'SizeZoom', 'Fade', 'Dissolve', 'ImageDissolve', 'AlphaDissolve', 'CropMove', 'PushMove', 'Pixellate', 'OldMoveTransition', 'MoveTransition', 'MoveFactory', 'MoveIn', 'MoveOut', 'ZoomInOut', 'RevolveInOut', 'MultipleTransition', 'ComposeTransition', 'Pause', 'SubTransition', 'ADVSpeaker', 'ADVCharacter', 'Speaker', 'Character', 'DynamicCharacter', 'MultiPersistent', 'Action', 'BarValue', 'AudioData', 'Style', 'SlottedNoRollback', 'NoRollback', '_layout_class', 'Fixed', 'HBox', 'VBox', 'Grid', 'AlphaBlend', 'At', 'Color', 'color', 'menu', 'predict_menu', 'default_transition', 'mouse_visible', 'suppress_overlay', 'adv', 'predict_say', 'say', '_last_say_who', '_last_say_what', '_last_say_args', '_last_say_kwargs', '_cache_pin_set', '_predict_set', '_predict_screen', '_overlay_screens', '_in_replay', '_side_image_attributes', '_side_image_attributes_reset', '_ignore_action', '_quit_slot', '_screenshot_pattern', 'sys', 'store', 'gui', '_errorhandling', '_error_hyperlink_styler', '_error_hyperlink_function', '_m1__errorhandling__limit_lines', '_m1__errorhandling__format_traceback', '_m1__errorhandling__format_parse_errors', '_EditFile', '_CopyFile', '_m1__errorhandling__can_open_traceback', '_m1__errorhandling__TooltipAction', '_m1__errorhandling__Tooltip', '_m1__errorhandling__XScrollValue', '_m1__errorhandling__YScrollValue', '_m1__errorhandling__ErrorQuit', '_m1__errorhandling__EnterConsole', '_warper', 'audio', 'achievement', 'build', '_console', 'director', '_gamepad', 'iap', 'icon', 'layeredimage', 'Attribute', 'LayeredImage', 'LayeredImageProxy', 'Condition', 'ConditionGroup', '_renpysteam', 'updater', 'inline_tool', 'threading', 'time', 'debug_thread', 'Debugger', 'cdbg', 'dbg', '_ini_registry', 'INIFile', 'inifile_statement', 'renpy_command', 'inga_speaking', 'inga_speaking_small', 'inga_closeup_speaking', 'parmida_closeup_speaking', 'configparser', 'persistent', '_preferences', '_test', '_scan_audio_directory', '_scan_images_directory', '_window_during_transitions', '_default_with_callback', '_game_menu_screen', '_enter_menu', '_invoke_game_menu', 'DictEquality', 'FieldEquality', 'save_name', 'preferences', '_default_empty_window', 'extend', '_skip_indicator', '_predict_statements', '_predict_screens', 'name_only', '_side_image_tag', '_side_image_old', '_side_image_raw', '_side_image', '_side_image_prefix_tag', '_side_per_interact', 'SideImage', '_m1_00action_data__FieldNotFound', '_m1_00action_data__get_field', '_m1_00action_data__set_field', 'SetField', 'SetVariable', 'SetDict', 'SetScreenVariable', 'SetLocalVariable', 'ToggleField', 'ToggleVariable', 'ToggleDict', 'ToggleLocalVariable', 'ToggleScreenVariable', 'AddToSet', 'RemoveFromSet', 'ToggleSetMembership', '_windows_hidden', '_keymap_toggle_afm', '_toggle_skipping', 'toggle_skipping', '_keymap_toggle_skipping', '_help', '_screenshot', '_screenshot_callback', '_fast_skip', '_reload_game', '_launch_editor', '_developer', '_profile_once', '_memory_profile', '_progress_screen', '_init_language', '_InputValueAction', 'DisableAllInputValues', 'InputValue', 'VariableInputValue', 'ScreenVariableInputValue', 'FieldInputValue', 'DictInputValue', 'alt', 'sv', 'Play', 'Queue', 'Stop', 'SetMixer', 'SetMute', 'ToggleMute', 'PauseAudio', 'NullAction', 'Return', 'Jump', 'Call', 'Show', 'ToggleScreen', 'ShowTransient', 'Hide', '_weekday_name_long', '_weekday_name_short', '_month_name_long', '_month_name_short', '_strftime', '_m1_00action_file__slotname', '_m1_00action_file__newest_slot', '_m1_00action_file__unused_slot_name', 'FileCurrentPage', 'FileUsedSlots', 'FileLoadable', 'FileScreenshot', 'FileTime', 'FileJson', 'FileSaveName', 'FileNewest', 'FileSave', 'FileLoad', 'FileDelete', 'FileAction', '_predict_file_page', 'FilePage', 'FilePageName', 'FilePageNameInputValue', 'FileSlotName', 'FilePageNext', 'FilePagePrevious', 'FileTakeScreenshot', 'QuickSave', 'QuickLoad', 'ShowMenu', 'Start', 'MainMenu', '_confirm_quit', 'Quit', 'Skip', 'Help', 'InvertSelected', 'If', 'SelectedIf', 'SensitiveIf', 'Screenshot', 'HideInterface', 'OpenURL', 'With', 'Notify', 'Rollback', 'RollbackToIdentifier', 'RestartStatement', 'RollForward', 'GetTooltip', '_m1_00action_other__TooltipAction', '_m1_00screen__TooltipAction', 'Tooltip', 'Language', 'Replay', 'EndReplay', 'MouseMove', 'QueueEvent', 'Function', 'Confirm', 'Scroll', 'OpenDirectory', 'CaptureFocus', 'ToggleFocus', 'ClearFocus', 'GetFocusRect', '_notify_transform', 'StaticValue', 'AnimatedValue', 'DictValue', 'FieldValue', 'VariableValue', 'ScreenVariableValue', 'MixerValue', 'XScrollValue', 'YScrollValue', 'AudioPositionValue', '_locale_to_language_function', '_imagemap_auto_function', 'hyperlink_styler', 'hyperlink_function', 'hyperlink_sensitive', '_m1_00gallery__GalleryAllPriorCondition', '_m1_00gallery__GalleryArbitraryCondition', '_m1_00gallery__GalleryUnlockCondition', '_m1_00gallery__GalleryImage', '_m1_00gallery__GalleryButton', '_m1_00gallery__GalleryToggleSlideshow', '_m1_00gallery__GalleryAction', 'Gallery', '_SetRenderer', '_m1_00gltest__gl_test', '_gl_performance_test', '_math', '_BaseMatrix', 'ColorMatrix', '_MultiplyMatrix', 'IdentityMatrix', 'SaturationMatrix', 'TintMatrix', 'BrightnessMatrix', 'OpacityMatrix', 'ContrastMatrix', 'ColorizeMatrix', 'HueMatrix', 'InvertMatrix', 'SepiaMatrix', 'MouseDisplayable', '_m1_00musicroom__MusicRoomPlay', '_m1_00musicroom__MusicRoomRandomPlay', '_m1_00musicroom__MusicRoomTogglePlay', '_m1_00musicroom__MusicRoomTogglePause', '_m1_00musicroom__MusicRoomStop', 'MusicRoom', 'nvl_list', 'nvl_variant', '_m1_00nvl_mode__s', '_NVLEntry', '_m1_00nvl_mode__nvl_screen_dialogue', '_m1_00nvl_mode__nvl_show_screen', 'nvl_show_core', 'nvl_window', 'nvl_show', 'nvl_hide', 'nvl_erase', 'nvl_clear_next', 'NVLCharacter', 'nvl', 'nvl_narrator', 'nvl_clear', 'nvl_menu', 'NVLSpeaker', '_nvl_adv_callback', 'Placeholder', '_m1_00preferences__DisplayAction', '_m1_00screen__DisplayAction', '_DisplayReset', 'Preference', '_m1_00preferences__show_self_voicing', 'os', '_SplineInterpolator', 'SplineMotion', '_m1_00stylepreferences__preferences', '_m1_00stylepreferences__alternatives', '_m1_00stylepreferences__spdirty', '_m1_00stylepreferences__register_style_preference', '_m1_00stylepreferences__init', '_m1_00stylepreferences__update', '_m1_00stylepreferences__apply_styles', '_m1_00stylepreferences__check', '_m1_00stylepreferences__change_language', '_m1_00stylepreferences__set_style_preference', '_m1_00stylepreferences__get_style_preference', 'StylePreference', 'pygame_sdl2', '_TouchKeyboardTextInput', '_TouchKeyboardBackspace', '_TouchKeyboardReturn', '_touch_keyboard', '_voice', '_last_voice_play', 'voice', 'voice_sustain', 'voice_replay', 'voice_can_replay', 'SetVoiceMute', 'SetCharacterVolume', 'GetCharacterVolume', 'PlayCharacterVoice', 'ToggleVoiceMute', 'VoiceReplay', 'VoiceInfo', '_get_voice_info', '_voice_history_callback', 'reset', 'left', 'right', 'center', 'truecenter', 'topleft', 'topright', 'top', 'offscreenleft', 'offscreenright', 'default', '_moveleft', '_moveright', '_movetop', '_movebottom', '_define', 'define', '_ease_out_time_warp', '_ease_in_time_warp', '_ease_time_warp', '_m1_00definitions__MoveTransition', 'fade', 'dissolve', 'pixellate', 'wiperight', 'wipeleft', 'wipeup', 'wipedown', 'slideright', 'slideleft', 'slideup', 'slidedown', 'slideawayright', 'slideawayleft', 'slideawayup', 'slideawaydown', 'irisout', 'irisin', 'pushright', 'pushleft', 'pushup', 'pushdown', 'zoomin', 'zoomout', 'zoominout', 'vpunch', 'hpunch', 'blinds', 'squares', 'Swing', 'swing', '_narrator', 'adv_narrator', 'centered', 'vcentered', 'layout', '_layout', '_intra_jumps_core', '_intra_jumps', 'TransformMatrix', 'OffsetMatrix', 'RotateMatrix', 'ScaleMatrix', '_theme', 'theme', 'RoundRect', '_audio_eval', '_try_eval', '_window_auto', '_window_show', '_window_hide', '_window_auto_callback', '_init_window', 'GamepadExists', 'GamepadCalibrate', '_m1_00themes__AWTBox', '_m1_00themes__AWTButton', '_m1_00themes__AWTBullet', '_set_script_version', '_default_keymap']

**Comment by Gouvernathor** [comment]
Let's continue this on Discord if you don't mind, it will be easier.

**Comment by mal** [comment]
Tracked down to `define store.foo = ...` being able to break `store`. While it doesn't make a lot of sense to do this (should really use `default foo = ...`), the resulting errors (multiple because lots of things are now missing from `store`) point you at all sorts of things except for the real cause.

**Comment by mal** [comment]
Closing this PR in favour of a bug report (#5058).

**Pull request closed without merging**
