### PR TITLE
Relative designate for ATL properties

### PR DESCRIPTION
**Pull request by kyouryuukunn**
I allowed relative value for ATL properties which are numerical type and not None by adding property `rel_` prefix.

for example, The below 2 code is equivalent.

```
    show bg:
        xpos 0.5 
        linear 1.15 rel_xpos 0.1  knot -0.87 
```

```
    show bg:
        xpos 0.5 
        linear 1.15 xpos 0.6  knot -0.37 
```

### CODE REVIEW

**Comment by via-my** [comment]
Wow! That's really useful.

**Comment by renpytom** [comment]
I like the idea of this, but I'm not a huge fan of the syntax. I think a version of the syntax that might work better would be: 

```
xpos current + 10
ypos current - 20
```

Something like that, maybe?

**Comment by JSearUK** [comment]
Hmm. Is there a reason why the following might not be useable?
```py
xpos += 10
ypos -= 20
```

**Comment by PastryIRL** [comment]
Funnily enough, I just opened an issue #3311 that this PR addresses.
I've checked out the fork and it appears to be working perfectly. I'll adopt it until it's merged into master :)
As far as the syntax goes, I think the standard decrement/increment notation of `-=`/`+=` would be the best approach as it's the most commonly used.

**Comment by Booplicate** [comment]
I like the `+=`/`-=` approach. Short, informative, doesn't require to learn new keywords/syntax as it already exists in Python and other languages.

**Comment by Andykl** [comment]
I would like it, if it is also possible to use `xpos = 100`. Otherwise it may be a problem to remember `xpos += 100` to shift, but `xpos 100` to set.

**Comment by Andykl** [comment]
Tom's variant is backward incompatible due to
```
transform some(current):
    xpos current + 10
```

**Comment by renpytom** [comment]
My only issue with +=/-= is when you have more than one of them on a line, which Ren'Py encourages. 

```
linear 2.0 xpos += 5 ypos += 10
```

Looks weird to me. I'd be fine with allowing an optional = there, and perhaps it makes sense to allow the interpolations to take a block. This would look good as:

linear 2.0:
    alpha = .5
    xpos += 5
    ypos += 10

I think. @Andykl, what do you think?

**Comment by Andykl** [comment]
Yeah, it sounds great and acutally I was thinking to add this possibility because long lines are terrible.
@kyouryuukunn Do you will to make it or should I?

**Comment by renpytom** [comment]
(I am tired enough I didn't realize who was working on this.)

**Comment by kyouryuukunn** [comment]
Hello.

I think Pytom's idea is good.
Thank you, @Andykl. please make it.

The reason I chosed my syntax is it's difficult to change parser and it's easy to just add properties prefix

**Comment by renpytom** [comment]
I'd suggest for the implementation, have a new type, relative(), such that  += 100 is represented as relative(100) after the parser step. That could then be used by the Interpolation node to determine the new value based on the old one.

**Comment by Andykl** [comment]
Closing in favor of #3358

**Pull request closed without merging**
