### PR TITLE
Allow function list and None for function statement in ATL ant parameter of Transform

### PR DESCRIPTION
**Pull request by kyouryuukunn**
I allowed function list for function statement in ATL ant parameter of Transform.
This allows below code.  the minimum number is used when some functions return a number .
```
show test:
    function [func1, func2]
```

I also allowed None for function statement in ATL.
Now, below code can disable function.
```
show test:
    function function_test
    time 2.
    function None
```

### CODE REVIEW

**Comment by Gouvernathor** [comment]
Can this load a save made with the current `Transform(function=whatever)`, without raising exceptions ?
Considering the code, I'm 99% sure it errors out. Luckily, \_\_version__ and after_upgrade can solve it (I'll do it if this is accepted).

**Comment by mal** [comment]
I think this is the sort of thing better left for creators that need it to implement for themselves. In the provided implementation all the functions are re-run based on the one that wants to re-run the most, which may not always be desirable.

Here's an example creator-side implementation to support this use-case. It would require some Python knowledge to create initially, but once in place would present a simple to use interface:

```py
class multifn(object):
    def __init__(*args):
        self.fns = args

    def __call__(trans, st, at):
        min_fr = None
        for f in self.fns:
            fr = f(trans, st, at)
            if fr is not None and (min_fr is None or fr < min_fr):
                min_fr = fr
        return min_fr
```
```rpy
show test:
    function multifn(func1, func2)
```

**Comment by renpytom** [comment]
Mal's right. Composing functions is easy to do in Python, and I don't think there's a clear way of doing it like there is for Actions.

**Comment by kyouryuukunn** [comment]
OK, @renpytom, @Mal, I close.

**Pull request closed without merging**
