### PR TITLE
Add GVim editor support for launcher (not include automatic install)

### PR DESCRIPTION
**Pull request by visig9**
Please accept it ~

/(^w^)/

### CODE REVIEW

**Comment by FractalBobz** [comment]
Yes this.

Thank you for the work, I'll be happily using this.

**Comment by renpytom** [comment]
I apologize this is taking a while. I'm planning on integrating it at some point, but I need to figure out how to make Ren'Py work with editors that may or may not exist on the user's system.

**Comment by ShengYun** [comment]
@civalin Can you create a git repo which contains your vim-syntax files as a plugin so people can use Pathogen/Vundle to add it.

**Comment by civalin** [comment]
@ShengYun Sorry for late. I find one of original creater continue maintain this highlighter. Use this:

- https://github.com/chaimleib/vim-renpy

**Comment by ShengYun** [comment]
@civalin Thanks:)

**Comment by renpytom** [comment]
Closing this - I don't think this will ever merge without the automatic install, and gvim is not something I'd offer for auto-install.

**Pull request closed without merging**
