### PR TITLE
removed obsolete documentation

### LINKED ISSUE #3990: Obsolete doc pages
- https://www.renpy.org/doc/html/android-packaging.html could use a HTTP redirect and be removed from the repo, as color.html and udd.html were
- https://www.renpy.org/doc/html/distributor.html looks obsolete and could be removed, or possibly merged in the changelog6 page

### PR DESCRIPTION
**Pull request by MintiClinti**
This change resolves #3990 by removing android.packaging.html and distributor.html. Information from distributor.html was merged with the changelog6 page.

### CODE REVIEW

**Review by Gouvernathor — APPROVED** [review]

**Comment by MintiClinti** [comment]
Hi, this is my first time working on open source. Should I close this pull request or leave it as opened?

**Comment by Gouvernathor** [comment]
Leave it open until Tom considers it.

**Comment by MintiClinti** [comment]
Awesome thank you

**Comment by renpytom** [comment]
Merged, thank you for your first contribution.

**Pull request merged**
