### PR TITLE
copypaste in renpy.input() just like the input in screens

### PR DESCRIPTION
**Pull request by Neyunse**
```
label start:
     code = renpy.input("Paste the secret code", copypaste=True)
     "The secret code is [code]"
```

### CODE REVIEW

**Comment by mal** [comment]
Seems to be missing the update to the `input` method signature?

**Comment by Neyunse** [comment]
> Seems to be missing the update to the `input` method signature?

I saw this function calls the class where the argument is, I don't know where an updater should go, I assume it will be updated in class. But I'm not sure, in a test I did it worked.

**Comment by Neyunse** [comment]
> > Seems to be missing the update to the `input` method signature?
> 
> I saw this function calls the class where the argument is, I don't know where an updater should go, I assume it will be updated in class. But I'm not sure, in a test I did it worked.

> It was a bit tricky to keep track of where the `input` was...

What I'm talking about is that I think it is updated here.

https://github.com/renpy/renpy/blob/2a66adb496f6b47786847325b930664a622a1448/renpy/display/behavior.py#L1359

And as I understand, this part sends the input properties to the screen.

https://github.com/renpy/renpy/blob/2a66adb496f6b47786847325b930664a622a1448/renpy/exports.py#L853

https://github.com/renpy/renpy/blob/2a66adb496f6b47786847325b930664a622a1448/renpy/display/screen.py#L1139

After that, I think it then calls the input class to pass it the arguments, but I'm not sure where.

**Comment by renpytom** [comment]
Merged, thank you. I'm also going to default this to true.

**Pull request merged**
