### PR TITLE
add combine option to extract dialogue

### PR DESCRIPTION
**Pull request by kyouryuukunn**
I added combine option to extract dialogue.
This combine special characters (%, {, [) which need to be double in dialogue into one. 
image

### CODE REVIEW

**Comment by Gouvernathor** [comment]
I'm not sure this should be optional. Maybe there should be a middle-ground happening all the time, extracting the dialogue lines exactly like they appear on screen, which means with {{ turned into {, but (unescaped) text tags removed.
This looks like what you programmed, so I think it should always be enabled, not with a checkbox and a command-line argument.
But, maybe don't remove them before getting a second opinion about it 😅

**Comment by kyouryuukunn** [comment]
[[ now doesn't combine. [[ and [ aren't distinct if combined.
"[test]" and "[[test]" is the same result

**Comment by renpytom** [comment]
I'm fine making this normal behavior, not an option.

**Comment by kyouryuukunn** [comment]
I removed the combine option. %% and {{ is always combined.

**Pull request merged**
