### PR TITLE
Character class callable for string type

### PR DESCRIPTION
**Pull request by AndriWilford**
This fixes issue #2682 .
Adds the ability for the string type conversion to also "call" a callable "who". Currently, only __call__ will attempt a callable who conversion.

### CODE REVIEW

**Comment by AndriWilford** [comment]
Apparently, using web interface to "update" a fork creates a dirty history.

Maybe just make the changes in the ..
   "Add function callable to string type"
 .. commit above oneself, rather than merge this request directly.

**Comment by Gouvernathor** [comment]
Passing a callable as a name to a dynamic character already works.
Examples : `define hyr = Character((lambda : _("Hyrulan") if believe_hyrulan else _("Sardaukar Soldier")), dynamic=True)`
```py
init python:
    def hyrname():
        return _("Hyrulan") if believe_hyrulan else _("Sardaukar Soldier")
define hyr = Character(hyrname, dynamic=True)
```
Both of these work.

**Comment by Gouvernathor** [comment]
You couls avoid some code duplication by replacing l. 1059 to 1067 with `rv = self.__unicode__()`.

**Comment by renpytom** [comment]
It looks good, and I don't think overloading unicode for this would be a good idea.

**Pull request merged**
