### PR TITLE
Fixes to French translation

### PR DESCRIPTION
**Pull request by Beuc**
I couldn't find the central point for the translations though. These strings also appear in "Tutorial" and to some extent in "Launcher". Should I replicate the changes there as well?

### CODE REVIEW

**Comment by renpytom** [comment]
Merged. Yes, the changes have to be replicated 3 times.

**Comment by Alexandre-T** [comment]
Le mot rembobinage est un bien meilleur choix que ce que j'avais proposé. Je pense que tu peux le répliquer. Je pense préférable d'utiliser des mots-clés comme : Sens, Rembobinage et Avance rapide. L'analogie avec les lecteurs vidéo est excellente. En revanche, «Rembobinage côté» n'est pas français. «Rembobinage» suffirait. À la rigueur «Sens du rembobinage». Dans tous les cas, c'est un meilleur choix que "Rollback"

The "Rembobinage" word is a better word than "Rollback". Some word like "Sens, Rembobinage, Avance rapide" could be used. But, "Rembobinage côté" isn't french. "Remboninage" is enough. "Sens du rembobinage" could be accepted. But "Rembobinage" is still a better choice than "Rollback".

**Comment by Beuc** [comment]
Hi Alexandre and thanks for your input,

"Sens" (way/direction) wouldn't be accurate because we're talking about which side ("côté") of the screen becomes active to perform a rollback - useful on mobile devices with no mousewheel.
In both cases this is a rollback, not a fast-forward (no "avance rapide").

"Rembobinage côté" is a compromise between accuracy and space constraints. It's used in the preferences screen that shows this block:
```
Rembobinage côté:
- Désactivé
- Gauche
- Droit
```

The full sentence (prompt + chosen value) becomes e.g. "Rembobinage coté droit" which is French.
This is not perfect but this manages to convey that "side" part, which is important to understand what this option is about.
What do you think?

**Comment by renpytom** [comment]
Please make sure I find out (probably via a new Pull Request) if this needs to be changed.

**Comment by Beuc** [comment]
Sure.
If there's no objection I'll replicate the patch for tutorial/launcher in a new pull request this week-end.

**Comment by Alexandre-T** [comment]
Your solution seems to be the best one.

**Comment by Beuc** [comment]
Done, see #1630 :)

**Pull request merged**
