### PR TITLE
Update Spanish translation

### PR DESCRIPTION
**Pull request by xavi-mat**
Everything is translated except the explanation comments in options.rpy, screens.rpy and gui.rpy. As always, I focus on the final player, not the developer.
I couldn't find the Spanish translation for "shoulder" (a button in some gamepads).
Please, @LuqueDaniel , can you have a look?

### CODE REVIEW

**Comment by LuqueDaniel** [comment]
I'm working in options.rpy, screens.rpy and gui.rpy.

I don't know how to translate "shoulder". We can use "Botón superior frontal"

From steam controller, they use "Botoón superior frontal derecho" and "Botón superior frontal izquierdo"
steam_controller

**Comment by xavi-mat** [comment]
Good idea. I'd use the abbreviations like steam does ("Botón **sup.** frontal **izq.**"...). A name too long could cause problems in the help screen.

**Comment by LuqueDaniel** [comment]
Yeah, you are right ^^

**Comment by renpytom** [comment]
Let me know when I can merge this, please.

**Comment by xavi-mat** [comment]
I've updated the translation for "Shoulder" buttons.
I think @renpytom can merge this PR and, when @LuqueDaniel finishes his work on the comments, he can open a new PR for that. If all of you agree.

**Comment by renpytom** [comment]
Let's do that, then. Merged.

**Pull request merged**
