### PR TITLE
Set crop_relative to False for integers.

### PR DESCRIPTION
**Pull request by loafylemon**
Attempts fixing #3508

### CODE REVIEW

**Comment by Booplicate** [comment]
I think there's some other unknown issue, and by fixing it this way you might just hide it.

Technically speaking, the `relative` function defined below should handle `int` and `absolute`. And it even works for the `crop` property, but not for the `corner`.

I think we should focus on why `crop (10, 10, 100, 100)` works, but `corner1 (10, 10)` + `corner2 (100, 100)` doesn't. Those should give the same result (unless I misunderstood).

Unsure if any of the following has any effect on this bug, but:

- Kind of weird the code does `crop = (x1, y1, x2-x1, y2-y1)` (reduces width/height) for corners, but not for crop?
- Also there's this code in `transform.py`:
```py
add_property("corner1", (float, float), None)
add_property("corner2", (float, float), None)
```
Maybe it should be changed to `(position, position)`?

**Comment by renpytom** [comment]
I'm working on this myself.

**Comment by Gouvernathor** [comment]
The fix in this PR is incorrect for the reasons stated above. I'll try to answer your points in order @Booplicate .

- The corners are documented as taking ints, not positions, so making them respond to relative coordinate would be a feature request. A legit one, in my view, but it's not a required fix for `corner1 (.5, .5)` to take a quarter of the child.
- corner2 is documented as being the coordinates of the bottom-right corner of the kept area, while crop[2:4] is the *size*, in pixels, of the cropped area. Not the same. So your example is inexact : `crop (10, 20, 100, 150)` should equate to `corner1 (10, 20)`, `corner2 (120, 170)`. Unless *I* misunderstood.
- The first code you quote is accurate because of what I just said, but the second one, with the floats, may be the answer to our problem. Will test it asap (not now). Feel free to lodge it as a PR (replacing them with `position`, might as well kill two birds with one stone).

**Comment by renpytom** [comment]
Obsoleted by 1de4027d7b5b481238c8f59c32dba36dcac04e20 .

**Pull request closed without merging**
