### PR TITLE
adding  tutorial\game\tl\indonesian\demo_pers~.rpy

### PR DESCRIPTION
**Pull request by pratomoastan**
adding  tutorial\game\tl\indonesian\demo_persistent.rpy.rpy

### CODE REVIEW

**Comment by vollschauer** [comment]
Wouldn't it be better to put all related files for the indonesian TL into one singe pull request?

**Comment by pratomoastan** [comment]
How ? 
Im New To Github .

**Comment by caryoscelus** [comment]
Simply commit to the branch of one pull request.

**Comment by pratomoastan** [comment]
okay, next time ill do that .

**Pull request merged**
