### PR TITLE
Porting ImageDissolve to the new matrixcolor system

### PR DESCRIPTION
**Pull request by Gouvernathor**
Allowed any displayable to take the role of the image controlling the transition.
Formerly only proper images were allowed, due to the use of the im. matrixes.

### CODE REVIEW

**Comment by Gouvernathor** [comment]
Maybe it's not the best place to suggest this (but I don't think it deserves raising an issue), how would you feel about giving (in the doc') a workaround for each documented "Image Manipulators" and `im.MatrixColor` functionality, since they are now all replaced with `Transform` or other ways to do it ?

I could write it in a pull request, but does it look interesting to you, giving such examples in the doc' ?

**Comment by renpytom** [comment]
I think it's too early to do this, unless config.gl2 is set. It's still possible to use the gl renderer - it's still the default. I'd like to get a little more experience with how well gl2 works before people switch over to it. 

I do think documentation about how to replace image manipulators would be good.

**Comment by Gouvernathor** [comment]
About the Matrix business - I can make an if-else switch, like `if config.gl2` the new 4*4 matrix is set then used, `else` the former one. Then, you can merge the pull request if you feel confident enough about gl2's reliability to perform that task.

**Comment by renpytom** [comment]
That seems like a good idea.

**Comment by Gouvernathor** [comment]
I'll get to work with the doc examples.

**Pull request merged**
