### PR TITLE
Fix Korean typos in the launcher. Add Korean translation for The Question.

### PR DESCRIPTION
**Pull request by lee-yunseok**
Just fixed a word in Korean.

### CODE REVIEW

**Comment by lee-yunseok** [comment]
Not complete yet.

**Comment by renpytom** [comment]
How are we for merging this? I'd like to make the release of Ren'Py 7.1.2 tomorrow, and I need to know if I should wait for this or not.

**Comment by lee-yunseok** [comment]
Yes please merge them.

**Comment by renpytom** [comment]
Merged, thanks.

**Pull request merged**
