### PR TITLE
Added the new Japanese linebreaking algorithm using Janome

### PR DESCRIPTION
**Pull request by kyouryuukunn**
Hello, pytom.

I allowed a user to use the new Japanese linebreaking algorithm "japanese-janome" using janome.

"japanese-janome" breaks line by `janome <https://github.com/mocobeta/janome>`_, 
which is Japanese Morphological Analysis library. This breaks the line
after a postpositional particle and below characters::

    )]）｝〕〉》」』】〙〗｠?!？！‼⁇⁈⁉、。

but, doesn't break line before below characters::

    ,)]）｝、〕〉》」』】〙〗〟’”｠»ゝゞァィゥェォッャュョヮヵヶぁぃぅぇぉっゃゅょゎゕゖㇰㇱㇲㇳㇴㇵㇶㇷㇸㇹㇷ゚ㇺㇻㇼㇽㇾㇿ々〻"ー‐゠–〜～?!‼⁇⁈⁉・:;/。.？！

A user should install janome and pkgutil into his game directory if he use this.::

    pip install --target game/python-packages janome

Then, copy pkgutil.py into the same python-packages directory from https://github.com/python/cpython/blob/2.7/Lib/pkgutil.py.

This is very natural but fairly slow line-breaking algorithm, so isn't recommended for huge amounts of text, such as in history.

A user should import janome in init block and place presplash.png into his game directory because it takes dozens of seconds.::

    init python:
        from janome.tokenizer import Tokenizer
        renpy.text.textsupport._janome_tokenize = Tokenizer().tokenize

janome is under Apache License 2.0 and uses the MeCab-IPADIC dictionary/statistical model, so I suggest using the below wording in his project's README file or App Store description to use janome:

    This program contains Ren'Py and below software.

    Ren'Py contains free software licensed under a number of licenses,
    including the GNU Lesser General Public License. A complete list of software
    is available at http://www.renpy.org/doc/html/license.html.

    janome (https://github.com/mocobeta/janome) Apache License 2.0 (http://www.apache.org/licenses/LICENSE-2.0)

    This program also includes MeCab-IPADIC (Nara Institute of Science and Technology)

And he should include a readable copy of
`NOTICE.txt <https://github.com/mocobeta/janome/blob/master/NOTICE.txt>`_ with
every copy of his Ren'Py distribute or display below wording in his application:

    This program includes MeCab-IPADIC (Nara Institute of Science and Technology)

### CODE REVIEW

**Comment by renpytom** [comment]
Hm... the talk of adding multiple seconds to the startup time scares me. What's causing that? 

I'm sort of wondering if it's the right idea to include this with Ren'Py, or have some sort of tool that can annotate the source or translations with zero-width space characters that provide breaking points, and then have a new annotator that tells Ren'Py to only break at such points.

**Comment by kyouryuukunn** [comment]
Japanese Morphological Analysis needs a big dictionary file about a part of speech.
That file is loaded when Tokenizer class is initialized and it takes time.
That class isn't called if a user doesn't set language to "japanese-janome".

It might be better to post this code on a forum if annotate_functions like ``annotate_unicode`` wasn't in a pyx file, but it needs to be compiled.

**Comment by kyouryuukunn** [comment]
Janome doesn't support python2 after v3.1.10, so I fixed document. 

pip install --target game/python-packages janome==0.3.10

And  I fixed some sample code in document.
I recommended to use janome for only say(nvl)_dialogue so that we can proceed efficiently 

    init python:
        from janome.tokenizer import Tokenizer
        renpy.text.textsupport._janome_tokenize = Tokenizer().tokenize
        style.say_dialogue.language = "japanese-janome"
        style.nvl_dialogue.language = "japanese-janome"

**Comment by kyouryuukunn** [comment]
Hello, Pytom.

I measured the load time. The long load time may be due to what Ren'py does.
I added below code and launched game.
```
init python:
    import time
    start = time.time()
    from janome.tokenizer import Tokenizer
    t = Tokenizer()
    test_time = time.time()-start
```
test_time was 20.25s when I installed janome into the game directory, but test_time was 1.77s when I installed it into lib/python2.7. 

I assume Ren'Py do something when a library is placed in a game directory, but I don't know the solution for it.

I also mesured the load times by python3 and janome v0.4.1 whose load time was improved from v0.4.0.
test_time was 1.94s by python2 and janome==0.3.10
test_time was 1.15s by python3 and janome==0.3.10
test_time was 0.34s by python3 and janome==0.4.1

The load will be faster when Ren'Py supports python3. I think the load time of Janome will not be problem If above problem was solved.

**Comment by kyouryuukunn** [comment]
Sorry, I didn't take non pc platform into acount.
In Android smartphone, it took 4,5 seconds to show text on say screen. In web, Ren'Py couldn't launch.
Caching linebreak is required before ditributing a game.

**Comment by kyouryuukunn** [comment]
This is resolved by #3733.

**Pull request closed without merging**
