### PR TITLE
toggle_afm

### PR DESCRIPTION
**Pull request by vollschauer**
Simply bind 'a' to toggle afm ...

### CODE REVIEW

**Comment by renpytom** [comment]
I'm not a fan of this. The problem is that it makes it too easy for a single errant keypress to switch on afm mode, and then the player has no idea how to get out of it*. Is toggling AFM such a frequent activity that it needs a keybinding?

* This was a problem with self-voicing mode, and we had to fix it by adding the popup.

**Comment by vollschauer** [comment]
I just thought it would be nice to have and how about merge it without binding it yet? 
So people could use it if they need a toggle afm.

**Comment by renpytom** [comment]
I'd be fine merging it without the keybinding, and without the _toggle_afm or toggle_afm functions - renpy.run(Preference("auto-forward mode", "toggle")) does the same thing, as does just accessing the preference directly. We don't need a function for it. The _keymap_toggle_afm function should stay.

**Comment by vollschauer** [comment]
Cool, I always learn something new :+1:  updated the file ... Thanks!

**Comment by renpytom** [comment]
Merged. Thanks.

**Pull request merged**
