### PR TITLE
Update options.rpy in ukrainian

### PR DESCRIPTION
**Pull request by Veydzher**
Changed strings.

### CODE REVIEW

**Comment by Veydzher** [comment]
ah, I can't understand why it comes with 3 additional commits I submited before. Is it must to be like that?

**Comment by Andykl** [comment]
It's likely that you have not rebased your master branch after last pull request so git automatically mereged current state to your local master branch. It does not matter for the merge.

**Comment by Veydzher** [comment]
Would 'Sync Fork' feature fix it?

**Comment by Andykl** [comment]
Yeah, I think before you add new commits to your master branch you need to sync fork.

**Pull request merged**
