### PR TITLE
Function to get the files inside the folder.

### PR DESCRIPTION
**Pull request by qTich**
The goal is to be able to receive the contents of the folder on the Android OS.

### CODE REVIEW

**Comment by renpytom** [comment]
Isn't this redundant to renpy.list_files() ?

**Comment by renpytom** [comment]
I'm not sure what you mean by "seems sad".  renpy.list_files is fast, as it's using game_files and common_files, not hitting the disk.

**Comment by KiloOscarSix** [comment]
Correct me if I'm wrong, but I think he means that `list_files()` returns all files and dirs while his function you can include a path argument.

**Comment by qTich** [comment]
I think that I agree with you about redundancy, since I received a value of `0.05-0.1 seconds` (on my phone) for `7717 files` when filtered based on `2-conditions`.

Rather, the question is in convenience, because for a personal computer you can use `os.listdir(path)`, and it will spend less time. Based on this, if I want to get a maximum speed optimization, then it should do so:
```py
files = [file for file in renpy.list_files() if file.startswith(path)] if renpy.android else os.listdir(path)
```
And it looks not very beautiful. In the decision that I proposed you can avoid such a case.

I think that it is possible to close the request, as this decision is not necessary.

**Comment by renpytom** [comment]
Files don't exist on android, so I'm closing this.

**Pull request closed without merging**
