### PR TITLE
Random fixes in the doc - 2

### PR DESCRIPTION
**Pull request by Gouvernathor**
Another version of #2507 without the messy merge commit and the matrixcolor fix

### CODE REVIEW

**Comment by Gouvernathor** [comment]
So the removal of the im. matrices is intentional ?

**Comment by Gouvernathor** [comment]
Also I've just noticed that Image-like Displayables are missing from the same doc page, is it also intentional ?

**Comment by renpytom** [comment]
Yes, in 7.4 there isn't much need for image manipulators, so I want to deemphasize them. 

It looks like image_like displayables are still there, unless I'm missing something.

**Comment by Gouvernathor** [comment]
Here is what I have on both versions of /displayables.html
Screenshot_121
Screenshot_122

**Pull request merged**
