### PR TITLE
Launcher's custom theme and fix typos in matrix documentation

### PR DESCRIPTION
**Pull request by Moshibit**

### CODE REVIEW

**Comment by Moshibit** [comment]
Launcher's custom theme and fix tipos in matrix documentation

**Comment by Moshibit** [comment]
I did this because the way to place a skin is not compatible with the dark theme. if you place a skin you cannot change to dark theme.

**Comment by renpytom** [comment]
Merged, thank you.

If you don't mind, please put the doc fixes and new features in separate PRs - it keeps things a bit more organized that way.

**Comment by Moshibit** [comment]
I'll keep it in mind next time.

**Pull request merged**
