### PR TITLE
Search archives in all searchpaths, not just gamedir

### PR DESCRIPTION
**Pull request by korden32**
It makes possible to put rpa archives in Android overwrite folder

### CODE REVIEW

**Comment by Gouvernathor** [comment]
gamedir should probably be added to that list because since the user can modify it at will and it's specified to be *additional* search paths. And I believe it should be searched first, to ensure backwards-compatibility.
So I'd advocate something like `for dir in [renpy.config.gamedir] + renpy.config.searchpath`

**Comment by korden32** [comment]
> gamedir should probably be added to that list 

Isn't it included in line 329? `renpy.config.searchpath = [ renpy.config.gamedir ]`

**Comment by Gouvernathor** [comment]
Indeed, it is, but it can be modified by the user, which can remove it from the list.
That being said, and unless I'm mistaken, the line you quoted and the one you modified folloxing each other, whatever the user have put in the list won't be taken in consideration, rendering your edit non-working. Have you tested it ?

**Comment by renpytom** [comment]
7.4.8 will be very android focused, and out soon after 7.4.7, so consideration of this PR will wait until after 7.4.7 is out.

**Comment by renpytom** [comment]
Merged, and I'll clean it up a bit. Thank you.

**Pull request merged**
