### PR TITLE
Fix unreachable code on handling exception

### PR DESCRIPTION
**Pull request by tdh8316**
Statements after `raise` seems to be unreachable.

### CODE REVIEW

**Comment by uyjulian** [comment]
`sys.exit(0)` is still unreachable.

**Comment by tdh8316** [comment]
Thanks! I think `sys.exit` is not required as the `raise` statement performs that action.

**Comment by renpytom** [comment]
I need to look at these more closely, since I think this might be spurious debug code.

**Comment by tdh8316** [comment]
Yes, there were other unreachable codes, which look like spurious debug code.
For instance:
```python
if False:
    ...
```
And I didn't edit these codes.

**Comment by renpytom** [comment]
This is a good catch, but it was more just debug code that didn't get removed.

**Comment by tdh8316** [comment]
Well, thanks for following up anyway.

**Pull request closed without merging**
