### PR TITLE
Disable automatic garbage collection during loading of pyanalysis/script/slast data

### PR DESCRIPTION
**Pull request by uyjulian**
Improves startup performance.

### CODE REVIEW

**Comment by renpytom** [comment]
I don't like the idea of entirely disabling garbage collection. What do you think about tweaking the settings, so it happens less often (or not at all). That's what we do after loading is finished, and I don't think we should be less aggressive about garbage collection when performance is less important (init) then when trying to keep up a framerate.

**Comment by uyjulian** [comment]
How about disabling automatic garbage collection at pickle loads?

**Comment by renpytom** [comment]
I think that makes more sense, though I think setting the GC threshold higher is better than a full disable.

**Comment by uyjulian** [comment]
I moved the disabled portions of automatic garbage collection to localized areas where pickle takes a while with automatic garbage collection enabled.

**Comment by renpytom** [comment]
I wrote  ab8c1bb4 as an alternative to this, since I think it makes sense to up the gc threshold, rather than disabling it entirely.

**Comment by uyjulian** [comment]
I think that's good.

**Pull request closed without merging**
