### PR TITLE
Again viewport focus

### PR DESCRIPTION
**Pull request by the66F95**
#5934 should be fixed while preserving the functionality of nested viewports and focusing children via keyboard.

### CODE REVIEW

**Comment by the66F95** [comment]
l.635 ff. of focus.py
```py
    if new_focus and isinstance(new_focus.widget, renpy.display.viewport.Viewport):
        new_focus = None
```
may need to be removed to make the entire viewport focusable for the mouse.
currently a dismiss displayable "under" the viewport is clickable "through" the viewports empty space.

**Comment by renpytom** [comment]
I rewrote this, and posted it as 9b290e07f. 

The one thing I don't get is the motivation for https://github.com/renpy/renpy/pull/5936/files#diff-5061088c6e29319dcf2d1f9d8438e9d4299c8f842b1952e037f505212564a57dR638 . That doesn't seem to do much, as it prevented the viewport from being focued, but that shouldn't matter. 

I'm not sure if that's what you meant in the comments above.

**Comment by the66F95** [comment]
after your changes i use now
```py
def mouse_handler(ev, x, y, default=False):
    """
    Handle mouse events, to see if they change the focus.

    `ev`
        If ev is not None, this function checks to see if it is a mouse event.
    """

    global pending_focus_type

    if grab:
        return

    if ev is not None:
        if ev.type not in (pygame.MOUSEMOTION, pygame.MOUSEBUTTONUP, pygame.MOUSEBUTTONDOWN):
            return
        else:
            pending_focus_type = "mouse"

    try:
        new_focus = renpy.display.render.focus_at_point(x, y)
    except renpy.display.layout.IgnoreLayers:
        new_focus = None

    if new_focus is None:
        new_focus = global_focus

    if new_focus and isinstance(new_focus.widget, renpy.display.viewport.Viewport) and new_focus.widget.draggable and not new_focus.widget.arrowkeys:
        new_focus = None

    return change_focus(new_focus, default=default)
```
otherwise the initial #5173 still persists.
you can't focus the viewports children via keyboard while the viewport is focused by the mouse.

**Comment by renpytom** [comment]
Another slightly different fix, in 2da8beecd7e3b2eefd67db1072f259a740e9738b, but I think this should work now.

**Pull request closed without merging**
