### PR TITLE
accessibility message changed to translatable string

### PR DESCRIPTION
**Pull request by Moshibit**

### CODE REVIEW

**Comment by renpytom** [comment]
Merged. Are you going to follow this up with the translation soon? I'd like to get 7.3 out the door today.

**Comment by Moshibit** [comment]
I just added that last string, and for now it would be everything, I already reviewed the translation three times.

**Comment by renpytom** [comment]
Sure, but we don't actually have the translation yet, as far as I can see. I want to make sure that's on the way, so I know when I can release.

**Comment by Moshibit** [comment]
The translation is ready

**Pull request merged**
