### PR TITLE
Use a NamedTuple for version_tuple (for #3755)

### PR DESCRIPTION
**Pull request by GiovanH**
Very simple draft that enables the convenience methods for indexing properties while remaining backwards compatible.

### CODE REVIEW

**Comment by GiovanH** [comment]
image

image

**Comment by GiovanH** [comment]
Only question I can think of is if `vc_version` is the best name for the fourth field. Maybe just `vc`?

**Comment by renpytom** [comment]
Probably 'commit' would be a good name for the last field. 

I'd also call it VersionTuple, and not SemVer. Ren'Py doesn't use Semantic Versioning.

**Comment by renpytom** [comment]
Merged. Thank you.

**Pull request merged**
